postgres.host=${POSTGRES_HOST}
postgres.port=${POSTGRES_PORT}
postgres.db.name=${POSTGRES_DB}

spring.datasource.url=jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.db.name}

server.port=${SPRING_PORT}
spring.application.name=relational-data-jdbc
